sudo: false

language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test:cover

branches:
  except:
    - gh-pages

cache:
  directories:
    - node_modules

addons:
   code_climate:
     repo_token: $CODECLIMATE_REPO_TOKEN
